---
version: '2'

services:
    redis:
        restart: always
        image: redis:alpine
        expose:
            - "6379"
        volumes:
            - ./redis:/data
    db:
        restart: always
        image: mysql:5.7
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=mymysqlpassword
            - MYSQL_DATABASE=lqhanzi
        volumes:
            - ./mysql:/var/lib/mysql
    web:
        restart: always
        #image: lqhanzi-base
        build: ./_docker

        environment:
            - http_proxy=http://wo.bj.intel.com:9119/
            - https_proxy=http://wo.bj.intel.com:9119/

        ports:
            - "8001:8000"
        links:
            - db:db
            - redis:redis
        volumes:
            - ./src:/src
        depends_on:
            - db
            - redis
